version: '3.8'

services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: metrics-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: metrics_management
      MYSQL_USER: metrics
      MYSQL_PASSWORD: metrics123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - metrics-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis
  redis:
    image: redis:7-alpine
    container_name: metrics-redis
    ports:
      - "6379:6379"
    networks:
      - metrics-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL for DolphinScheduler
  postgresql:
    image: postgres:13
    container_name: dolphinscheduler-postgres
    environment:
      POSTGRES_DB: dolphinscheduler
      POSTGRES_USER: dolphinscheduler
      POSTGRES_PASSWORD: dolphinscheduler123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - metrics-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dolphinscheduler"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Zookeeper for DolphinScheduler
  zookeeper:
    image: zookeeper:3.8
    container_name: dolphinscheduler-zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_logs:/datalog
    networks:
      - metrics-network
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 5

  # DolphinScheduler API
  dolphinscheduler-api:
    image: apache/dolphinscheduler-api:3.2.1
    container_name: dolphinscheduler-api
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_HOST: postgresql
      DATABASE_PORT: 5432
      DATABASE_USERNAME: dolphinscheduler
      DATABASE_PASSWORD: dolphinscheduler123
      DATABASE_DATABASE: dolphinscheduler
      ZOOKEEPER_QUORUM: zookeeper:2181
      REGISTRY_TYPE: zookeeper
    ports:
      - "12345:12345"
    networks:
      - metrics-network
    depends_on:
      postgresql:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12345/dolphinscheduler/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  postgres_data:
  zookeeper_data:
  zookeeper_logs:

networks:
  metrics-network:
    driver: bridge