version: '3.8'

services:
  # Neo4j 图数据库
  neo4j:
    image: neo4j:5-community
    container_name: metrics-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      # 设置默认用户名和密码
      - NEO4J_AUTH=neo4j/metrics123
      # 允许从任何主机访问
      - NEO4J_server_default__advertised__address=localhost
      - NEO4J_server_bolt_advertised__address=localhost:7687
      - NEO4J_server_http_advertised__address=localhost:7474
      # 配置内存
      - NEO4J_server_memory_heap_initial__size=512M
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=512M
      # 启用 APOC 插件
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      # 安全设置
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./scripts/neo4j-init:/var/lib/neo4j/init
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "metrics123", "MATCH (n) RETURN COUNT(n) LIMIT 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - metrics-network

  # Neo4j 数据初始化容器
  neo4j-init:
    image: neo4j:5-community
    container_name: metrics-neo4j-init
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_AUTH=neo4j/metrics123
    volumes:
      - ./scripts/neo4j-init:/init
    command: >
      bash -c "
        echo '等待 Neo4j 完全启动...';
        sleep 10;
        echo '开始导入指标血缘数据...';
        cypher-shell -a bolt://neo4j:7687 -u neo4j -p metrics123 -f /init/init-metrics-lineage.cypher;
        echo '数据导入完成！';
      "
    networks:
      - metrics-network

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

networks:
  metrics-network:
    driver: bridge
    name: metrics-network